#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
runcmd:
  - sudo apt update
  - sudo apt install -y nginx
  - echo "<html><body><h2>Welcome to Azure! My name is $(hostname).</h2></body></html>" | sudo tee -a /var/www/html/index.html
